name: fit
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - jupyterlab
  - jupytext
  - notebook
  - matplotlib
  - scikit-image
  - jupyter-book
  - pooch
  - pyqt=5.*
  - scikit-learn
  - ipywidgets
  - seaborn
  - cookiecutter
  - cellpose
  - zarr
  - torchvision
  - napari-animation
  - napari=0.5.0
  - napari-pdf-reader
  - napari-ome-zarr
  - zarpaint
  - affinder
  - pip:
    - mrcfile
    - starfile
      # - git+https://github.com/jni/napari.git@fix-translate-bug
